import Foundation

/// Ja-JP. Keys are the English copy-deck strings. Plain, warm Japanese in
/// the same register as the English: no alarm, no marketing, no em-dashes,
/// no exclamation points. Kibi's short lines are re-authored, not translated.
/// Drafted for native review before store submission.
extension Loc {
    static let jaStrings: [String: String] = [
        // 11.1 Onboarding
        "Most of what fills a developer's disk is caches and build output.": "開発者のディスクを埋めているのは、大部分がキャッシュとビルド生成物です。",
        "Elbowroom separates them from your files, then cleans up or offloads.": "Elbowroom がそれらをあなたのファイルと区別し、削除またはオフロードします。",
        "Continue": "続ける",
        "Local processing": "この Mac の中だけで処理します",
        "Scanning, explanations, and AI answers all run on this Mac. Elbowroom does not touch the network while it scans. Usage statistics are anonymous, optional, and off by default.": "スキャンも説明も AI の回答も、すべてこの Mac の上で動きます。スキャン中に Elbowroom がネットワークに触れることはありません。利用統計は匿名かつ任意で、初期設定ではオフです。",
        "Let Elbowroom see the whole disk": "Elbowroom にディスク全体を見せてください",
        "One switch in System Settings lets Elbowroom count everything, with no permission pop-ups during the scan. What it reads never leaves this Mac.": "システム設定のスイッチ 1 つで、Elbowroom がすべてを数えられるようになります。スキャン中に許可のポップアップは出ません。読み取った内容がこの Mac の外に出ることはありません。",
        "Start the scan": "スキャンを開始",
        "Full Disk Access is already on.": "フルディスクアクセスはすでにオンです。",
        "Start with just my home folder": "まずホームフォルダだけで始める",
        "Waiting for the switch": "スイッチを待っています",
        "macOS may ask to quit and reopen Elbowroom. Let it: the scan starts right where you left off.": "macOS が Elbowroom の再起動を求めることがあります。そのまま任せてください。スキャンは続きから始まります。",
        "Relaunch Elbowroom": "Elbowroom を再起動",
        "Drag Elbowroom into the list, then turn it on.": "Elbowroom をリストにドラッグして、スイッチをオンにしてください。",
        "A few folders need your OK": "いくつかのフォルダに許可が必要です",
        "macOS asks before Elbowroom can look inside these. Allow each one and nothing goes missing from the count.": "Elbowroom がこれらの中を見る前に、macOS が確認します。それぞれ許可すると、数え漏れがなくなります。",
        "Elbowroom won't see files outside your home folder.": "ホームフォルダの外にあるファイルは Elbowroom から見えません。",
        "Not visible for now": "今は見えません",
        "Desktop": "デスクトップ",
        "Documents": "書類",
        "Downloads": "ダウンロード",
        "Photos library": "写真ライブラリ",
        "Other apps' data": "ほかのアプリのデータ",
        "You can safely get back %@ today.": "今日、%@ を安全に取り戻せます。",
        "You can safely get back": "今日、安全に取り戻せるのは",
        "today.": "です。",
        "Every item is identified and rated for safety.": "すべての項目が識別され、安全度が付いています。",
        "Low on space. Elbowroom picked the quickest safe items first.": "空きが少なくなっています。すぐ効く安全な項目から選んであります。",
        "Not much to reclaim right now. Elbowroom will watch for growth.": "今は取り戻せるものが多くありません。増えたら Elbowroom が気づきます。",
        "Reclaim now": "今すぐ取り戻す",
        "Open the map": "マップを開く",
        "Set up an offload drive": "オフロード用ドライブを設定",
        "Free up %@ in about a minute": "約 1 分で %@ を空ける",
        "Some areas weren't visible. Expand access": "見えない場所がありました。アクセスを広げる",

        "The quickest safe items, pre-checked.": "すぐ効く安全な項目に、チェックを入れてあります。",
        "A plan you approve first.": "実行の前に、あなたが計画を確認します。",
        "A treemap of the whole disk.": "ディスク全体のツリーマップ。",
        "Move big folders to an external drive.": "大きなフォルダを外付けドライブへ。",
        "Keep them one link away.": "リンク 1 つ分の距離に置いておけます。",
        "Reverses every move, then Elbowroom can be deleted cleanly.": "すべての移動を元に戻し、Elbowroom をきれいに削除できるようにします。",

        // 11.2 Ticker
        "Found %@ of Xcode build products": "Xcode のビルド生成物 %@ を発見",
        "%1$@ of simulator devices, unused since %2$@": "シミュレータのデバイス %1$@(%2$@から未使用)",
        "%@ of Rust build folders. Your next build remakes these.": "Rust のビルドフォルダ %@。次のビルドで作り直されます。",
        "%@ of package caches. These download again when needed.": "パッケージキャッシュ %@。必要になれば再ダウンロードされます。",
        "%1$@ in iPhone backups from %2$@": "%2$@の iPhone バックアップに %1$@",
        "Snapshots hold %@. macOS thins them on its own.": "スナップショットが %@ を保持。macOS が自動で間引きます。",
        "Large disk. This can take a few minutes.": "大きなディスクです。数分かかることがあります。",
        "%@ of JavaScript packages. These install again when needed.": "JavaScript パッケージ %@。必要になれば再インストールされます。",
        "Found %2$@ of %1$@": "%1$@ %2$@ を発見",

        // 11.3 Tiers
        "Deleted safely. It is re-created on demand.": "安全に削除できます。必要になれば自動で再生成されます。",
        "Rebuilt from your project by its own tools.": "プロジェクトのツールが次回のビルドで再生成します。",
        "Owned by another app. Elbowroom opens that app's controls.": "他のアプリの管理領域です。Elbowroom はそのアプリの設定画面を開きます。",
        "Your files. Elbowroom never suggests changes here.": "あなたのファイルです。Elbowroom が変更を提案することはありません。",
        "Cache": "キャッシュ",
        "Derived": "生成物",
        "App-managed": "アプリ管理",
        "Personal": "個人ファイル",
        // 11.4 Reclaim
        "Reclaim plan": "取り戻す計画",
        "The next %1$@ run downloads about %2$@ again (%3$@ on your connection)": "次に %1$@ を実行すると約 %2$@ を再ダウンロードします(お使いの回線で %3$@)",
        "Keep in Trash for 7 days": "7 日間ゴミ箱に残す",
        "Reclaim %@": "%@ を取り戻す",
        "%@ reclaimed. Receipt saved.": "%@ を取り戻しました。控えを保存しました。",
        "Elbowroom skipped %d item:": "%d 件をスキップしました:",
        "Elbowroom skipped %d items:": "%d 件をスキップしました:",
        "Rebuilding this next time takes about %@.": "次に作り直すときは約 %@ かかります。",
        "OK": "OK",
        "Cancel": "キャンセル",
        "%@ safely reclaimable": "%@ を安全に取り戻せます",
        "safely reclaimable": "安全に取り戻せます",
        "%1$d item · %2$@": "%1$d 件 · %2$@",
        "%1$d items · %2$@": "%1$d 件 · %2$@",
        "Reclaim": "取り戻す",
        "Offload": "オフロード",
        "Clear": "解除",
        "Stopped. %d item was already reclaimed and stays reclaimed.": "中断しました。%d 件はすでに取り戻し済みで、そのままです。",
        "Stopped. %d items were already reclaimed and stay reclaimed.": "中断しました。%d 件はすでに取り戻し済みで、そのままです。",

        // 11.5 Stash
        "%@/s. Fast enough for build folders.": "%@/秒。ビルドフォルダにも十分な速さです。",
        "%@/s. Fine for archives and model weights, too slow for build folders.": "%@/秒。アーカイブやモデルには十分ですが、ビルドフォルダには遅めです。",
        "Include the offload folder in Time Machine? Everything in it can be rebuilt, so skipping it is fine.": "オフロードフォルダを Time Machine に含めますか。中身はすべて再生成できるため、外しても問題ありません。",
        "Skip It": "外す",
        "Include It": "含める",
        "Moves back the same way, any time.": "いつでも同じ手順で戻せます。",
        "%@ is running. Quit it first.": "%@ が起動中です。先に終了してください。",
        "Offloaded. %@ freed.": "オフロードしました。%@ が空きました。",
        "%1$@ is on '%2$@'. Connect it before building.": "%1$@ は「%2$@」にあります。ビルドの前に接続してください。",
        "%1$@ just opened. Its %2$@ is on '%3$@'.": "%1$@ が起動しました。その %2$@ は「%3$@」にあります。",
        "Two versions of %@": "%@ が 2 つあります",
        "Merge newer onto the drive and relink": "新しい方をドライブへ取り込み、リンクし直す",
        "Keep local": "この Mac の方を使う",
        "%@ is still using the drive.": "%@ がまだドライブを使っています。",
        "Set up this Mac like your last one?": "前の Mac と同じように整えますか。",
        "Move everything back": "すべてローカルへ戻す",
        "Everything is back on the internal disk. Elbowroom can be removed cleanly now.": "すべて内蔵ディスクに戻りました。Elbowroom はきれいに削除できます。",
        "Elbowroom needs APFS to move things safely": "安全に移すには APFS が必要です",
        "Erase & Format": "消去してフォーマット",
        "Set up offloading": "オフロードを設定",
        "Pick an external drive. Elbowroom moves large derived folders there and leaves a working link in place.": "外付けドライブを選択してください。大きな生成物フォルダを移動し、元の場所には動作するリンクを残します。",
        "No external drives found. Plug one in and it appears here.": "外付けドライブが見つかりません。接続するとここに表示されます。",
        "Measuring the drive": "ドライブを計測中",
        "Use This Drive": "このドライブを使う",
        "not connected": "未接続",
        "Connect '%@' first.": "先に「%@」を接続してください。",
        "on '%1$@' · %2$@ offloaded": "「%1$@」上 · %2$@ をオフロード済み",
        "moved %@": "%@ に移動",
        "Clean Up": "クリーンアップ",
        "Asking the tool what can go": "削除できるものをツールに確認中",
        "Elbowroom will run:": "Elbowroom は次を実行します:",
        "Run (%@)": "実行 (%@)",
        "These delete through the tool itself, not the Trash. Put Back does not apply.": "これらはツール自体を通じて削除され、ゴミ箱には入りません。「元に戻す」は使えません。",
        "The tool for this is not installed.": "このためのツールがインストールされていません。",
        "The tool did not answer in time.": "ツールが時間内に応答しませんでした。",
        "Start the container app first.": "先にコンテナアプリを起動してください。",
        "%d unavailable simulators": "利用できないシミュレータ %d 台",
        "Their runtimes are gone. Xcode cannot boot them again.": "ランタイムが削除済みのため、Xcode はもう起動できません。",
        "never booted": "一度も起動していません",
        "superseded by %@": "%@ に置き換えられました",
        "Stopped containers": "停止中のコンテナ",
        "Exited containers and their writable layers.": "終了したコンテナとその書き込みレイヤー。",
        "Unused images": "未使用のイメージ",
        "Images no container is using.": "どのコンテナも使っていないイメージ。",
        "Pulling them back takes time and bandwidth.": "取り直すには時間と帯域がかかります。",
        "Build cache": "ビルドキャッシュ",
        "Layers docker build keeps for reuse.": "docker build が再利用のために保持するレイヤー。",
        "Unused volumes": "未使用のボリューム",
        "Volumes no container references.": "どのコンテナからも参照されていないボリューム。",
        "Volumes can hold data you created. Check this only if you are sure.": "ボリュームにはあなたが作成したデータが入っていることがあります。確実な場合のみチェックしてください。",
        "The row's %@ is Docker's virtual disk: your images and volumes plus the small Linux system they run in. These rows free space inside it, and Docker hands freed space back to macOS automatically.": "この行の %@ は Docker の仮想ディスクです。中身はあなたのイメージとボリューム、そしてそれらを動かす小さな Linux システムです。ここの行はその内部を空け、空いた分は Docker が自動的に macOS へ返します。",
        "%1$@ (%2$@) is current and stays.": "%1$@（%2$@）は最新のため残ります。",
        "Copies the image to '%@' first, then deletes it here. Adding back needs no download.": "先にイメージを「%@」へコピーしてから、ここから削除します。戻すときのダウンロードは不要です。",
        "The current runtime. Simulators stop working until you add it back.": "現在のランタイムです。戻すまでシミュレータは動きません。",
        "On '%@'. Adds back without downloading.": "「%@」上にあります。ダウンロードせずに戻せます。",
        "Sealed by macOS. Offloads through Xcode's tool instead.": "macOS により保護されています。代わりに Xcode のツールを通じてオフロードします。",
        "%1$d offloaded · %2$@ on '%3$@'": "%1$d 件をオフロード済み · 「%3$@」に %2$@",
        "Add Back": "戻す",
        "%d devices used recently stay.": "最近使った %d 台のデバイスは残ります。",
        "Old versions and stale downloads": "古いバージョンと古いダウンロード",
        "brew cleanup keeps what is linked and removes the rest.": "brew cleanup はリンク中のものを残し、それ以外を削除します。",
        // Time Machine local snapshots
        "Local safety snapshots": "ローカルの安全スナップショット",
        "made %@": "作成: %@",
        "These are this Mac's local restore points. The next backup runs longer while Time Machine takes fresh ones.": "これはこの Mac のローカル復元ポイントです。次のバックアップは、Time Machine が新しいスナップショットを作り直すぶん長くかかります。",
        "Your backup history on '%@' is separate and stays untouched.": "「%@」にあるバックアップ履歴は別物で、ここでは一切触れません。",
        "No backup destination is set up, so these snapshots are this Mac's only file history. Deleting them removes the way back to recent versions.": "バックアップ先が設定されていないため、これらのスナップショットがこの Mac の唯一のファイル履歴です。削除すると、最近のバージョンへ戻る手段がなくなります。",
        "Up to %@ comes back. Elbowroom measures the exact amount after the run.": "最大 %@ が戻ります。正確な量は実行後に Elbowroom が測定します。",
        "A backup is running right now. Try again after it finishes.": "いまバックアップが実行中です。終わってからもう一度どうぞ。",
        "%d update snapshot stays. The macOS updater owns it and clears it when the update finishes.": "%d 個のアップデート用スナップショットは残ります。macOS のアップデータが所有し、アップデート完了時に自動で消します。",
        "%d update snapshots stay. The macOS updater owns them and clears them when the update finishes.": "%d 個のアップデート用スナップショットは残ります。macOS のアップデータが所有し、アップデート完了時に自動で消します。",
        "Trim these automatically": "自動で間引く",
        "macOS has no off switch for local snapshots. When new ones appear, Elbowroom deletes them once the backup finishes. Backups start fresh and can run longer.": "macOS にはローカルスナップショットを止めるスイッチがありません。新しいものが現れたら、バックアップ完了後に Elbowroom が削除します。バックアップは毎回まっさらから始まり、時間が長くかかることがあります。",
        "Deleted %d local snapshot": "%d 個のローカルスナップショットを削除しました",
        "Deleted %d local snapshots": "%d 個のローカルスナップショットを削除しました",
        "Run (up to %@)": "実行 (最大 %@)",
        "macOS keeps a few local snapshots beside your real backups and thins them on its own. Deleting them frees the space they pin.": "macOS は本来のバックアップとは別にローカルスナップショットをいくつか保ち、自動で間引きます。削除すると、それらが抱えている容量が戻ります。",
        "Full Disk Access": "フルディスクアクセス",
        "Lets the scan read protected folders like Mail and Safari. macOS asks you to grant it in System Settings.": "Mail や Safari などの保護されたフォルダをスキャンで読めるようになります。付与はシステム設定から行います。",
        "Open System Settings": "システム設定を開く",
        "Granted": "許可済み",
        "Hide": "隠す",
        "Suggested moves": "提案する操作",
        "%d hidden": "%d 件を非表示中",
        "Show": "表示",
        "%@ cache": "%@ のキャッシュ",
        "%d locations": "%d か所",
        "%1$@ of %2$@ offloaded": "%2$@ 中 %1$@ をオフロード済み",
        "%@ moved, but the old copy is still on the internal disk. Its space is not freed yet.": "%@ は移動済みですが、古いコピーがまだ内蔵ディスクに残っています。その分の空きはまだ増えていません。",
        "Try Again": "もう一度",
        "Moving back %@": "%@ を戻しています",
        "Network volumes are not supported yet.": "ネットワークボリュームにはまだ対応していません。",
        "This is an internal partition.": "内蔵パーティションです。",
        "Local": "ローカル",
        "Offloaded": "オフロード済み",
        "A tool rebuilt this folder on the internal disk while the drive was away. Both versions exist now.": "ドライブが外れている間に、ツールがこのフォルダを内蔵ディスクに作り直しました。今は両方が存在します。",
        "On this Mac": "この Mac",
        "On the drive": "ドライブ側",
        "newer": "新しい",
        "Merging": "取り込み中",
        "Part of this folder is still in iCloud. Download it first.": "このフォルダの一部はまだ iCloud にあります。先にダウンロードしてください。",
        "The Stash drive is not connected.": "Stash ドライブが接続されていません。",

        // 11.6 Explainers
        "macOS keeps files it can delete on its own when space runs low. Finder often counts this space as available. Elbowroom lists it separately.": "空きが減ると macOS が自分で消せるファイルです。Finder はこの分を空きに数えることがあります。Elbowroom は分けて表示します。",
        "macOS makes these local backups and thins them on its own. The command below thins them now.": "macOS が作るローカルバックアップで、自動で間引かれます。下のコマンドで今すぐ間引けます。",
        "What macOS groups under System Data, item by item. The largest parts here: %@.": "macOS が「システムデータ」とまとめているものの内訳です。大きいのは %@ です。",

        // 11.7 Paywall
        "Elbowroom Pro": "Elbowroom Pro",
        "Unlimited reclaim": "取り戻し無制限",
        "Offloading to external drives": "外付けドライブへのオフロード",
        "Background monitoring and update planning": "バックグラウンド監視とアップデート計画",
        "New-Mac migration": "新しい Mac への移行",
        "$19.99, one time. No subscription.": "$19.99 の買い切り。サブスクリプションはありません。",
        "Unlock Elbowroom Pro": "Elbowroom Pro を購入",
        "Keep the free tools": "無料のまま使う",
        "You've used your free 10 GB.": "無料枠の 10 GB を使い切りました。",
        "The App Store is not reachable from this build.": "このビルドからは App Store に接続できません。",
        "Restore Purchase": "購入を復元",
        "Enable Pro on this Mac": "この Mac で Pro を有効にする",
        "Pro is enabled on this Mac.": "この Mac では Pro が有効です。",
        "This build did not come from the App Store, so Pro unlocks locally and free.": "このビルドは App Store 経由ではないため、Pro はこの場で無料で有効にできます。",

        // 11.8 Errors
        "That move didn't finish. Nothing was lost. Try again?": "移動が完了しませんでした。失われたものはありません。もう一度試しますか。",
        "The copy didn't match, so Elbowroom kept the original. Try again?": "コピーが一致しなかったため、元のままにしてあります。もう一度試しますか。",
        "'%@' ran out of room mid-move. The original is untouched.": "移動の途中で「%@」の空きがなくなりました。元のデータはそのままです。",
        "macOS blocked a few areas. Everything else is accurate.": "いくつかの場所は macOS に遮られました。それ以外は正確です。",

        // 11.9 Kibi lines (re-authored)
        "Nothing to clean right now.": "今は掃除するものがありません。",
        "No receipts yet.": "控えはまだありません。",
        "Nothing offloaded yet.": "オフロードされたものはまだありません。",
        "No changes this week.": "今週は変化がありません。",
        "No matches.": "見つかりません。",

        // Steward
        "macOS %1$@ needs %2$@. Elbowroom has a %3$d-minute plan. Review it?": "macOS %1$@ には %2$@ 必要です。Elbowroom に約 %3$d 分の計画があります。確認しますか。",
        "Room for macOS %@": "macOS %@ のための空き",
        "Ready to update. %@ free.": "アップデートの準備ができました。空きは %@ です。",
        "Open Elbowroom": "Elbowroom を開く",
        "Reclaimable now: %@": "今すぐ取り戻せる分: %@",
        "Safe Eject": "安全に取り外す",
        "Pause a while": "しばらく休ませる",
        "Quit Elbowroom": "Elbowroom を終了",
        "Room for an update": "アップデートのための空き",
        "The update needs %1$@ more than is free. This plan clears %2$@ in about %3$d minutes.": "アップデートには空きがあと %1$@ 足りません。この計画で約 %3$d 分、%2$@ を空けられます。",
        "Move to the Stash": "Stash へ移す",
        "Also worth a look (through their own apps, not counted above)": "あわせて確認する価値のあるもの(各アプリから操作。上の合計には含みません)",
        "Plan for an update": "アップデートに備える",
        "Room for the update": "アップデートのための空き",
        "%@ free": "空き %@",
        "Free": "空き",
        "%1$@ free of %2$@": "%2$@ 中 空き %1$@",
        "Ready to reclaim": "取り戻せる容量",
        "Caches and derived data apps rebuild on their own. Nothing personal is touched without you choosing it.": "キャッシュとビルド生成物は、アプリが自分で作り直します。あなたが選ばない限り、個人のファイルには触れません。",
        "Offload instead": "代わりにオフロード",
        "Biggest wins right now": "いま効き目の大きい項目",
        "All %d items": "全 %d 件",
        "Add to Plan": "計画に追加",
        "In plan": "計画に追加済み",
        "Growing this week": "今週の増減",
        "↓ means Elbowroom already trimmed it back.": "↓ は Elbowroom がすでに整理し終えた分です。",
        "The next macOS update needs about %1$@ free. You have %2$@, so you are covered.": "次の macOS アップデートには約 %1$@ の空きが必要です。現在 %2$@ あるので大丈夫です。",
        "All time": "累計",
        "returned to this Mac.": "をこの Mac に取り戻しました。",
        "sorted by size": "サイズ順",
        "Everything here is rebuilt or recoverable": "ここにあるものは、作り直せるか元に戻せます",
        "click a region to dig in": "クリックで掘り下げる",
        "%1$@ scanned · %2$@ free": "スキャン済み %1$@ · 空き %2$@",
        "tint = tier · area = size": "色 = 安全度 · 面積 = サイズ",
        "Switch light and dark": "ライトとダークを切り替え",
        "The current runtime. Xcode downloads about %@ again before simulators next run.": "現在使用中のランタイムです。削除すると、次にシミュレータを使う前に Xcode が約 %@ を再ダウンロードします。",
        "Images your containers use": "コンテナが使用中のイメージ",
        "Volumes in use": "使用中のボリューム",
        "Running containers": "実行中のコンテナ",
        "Docker's Linux system": "Docker の Linux システム",
        "Full sweep of everything unused": "未使用のものを一括整理",
        "docker system prune removes every unused image, container, volume, and build cache in one pass.": "docker system prune が、未使用のイメージ、コンテナ、ボリューム、ビルドキャッシュを一度に削除します。",
        "Simulator": "シミュレータ",
        "Runtimes, simulated devices, and caches for Xcode's simulators, together.": "Xcode のシミュレータのランタイム、仮想デバイス、キャッシュをまとめた項目です。",
        "Simulator dyld caches": "シミュレータの dyld キャッシュ",
        "Prebuilt loader caches. The next simulator boot remakes what it needs.": "事前構築されたローダキャッシュです。次にシミュレータを起動したとき、必要な分が作り直されます。",

        // Lenses
        "Click to look closer": "クリックで詳しく見る",
        "Look Closer": "詳しく見る",
        "Reclaim All": "すべて取り戻す",
        "Photos, VMs, installers, and old downloads hide in here. Lenses name them.": "写真、仮想マシン、インストーラ、古いダウンロードがこの中に隠れています。レンズが名前を付けます。",
        "%@ named so far": "ここまでに %@ に名前が付きました",
        "Nothing recognizable in Everything else. It is genuinely yours.": "「そのほか」に見覚えのある形はありませんでした。純粋にあなたのファイルです。",
        "%1$d photos, %2$d videos · %3$@": "写真 %1$d 枚、動画 %2$d 本 · %3$@",
        "%@ is already installed": "%@ はインストール済みです",
        "%d large file": "大きいファイル %d 件",
        "%d large files": "大きいファイル %d 件",
        "Byte-identical in both places, verified": "両方の場所でバイト単位で同一(確認済み)",
        "Its unpacked folder sits right beside it": "展開済みのフォルダがすぐ隣にあります",
        "%@ project": "%@ プロジェクト",
        "Nothing inside touched since %@": "%@ から中身に変化はありません",
        "Last used %@": "最終使用は %@",
        "Re-downloadable from its hub": "配布元から再ダウンロードできます",
        "Reinstalls from Steam · updated %@": "Steam から再インストール可能 · 更新は %@",
        "Named by a lens": "レンズが名前を付けた項目",
        "Found inside Everything else. You saw what it is; you decide.": "「そのほか」の中で見つかりました。正体を確認した上で、あなたが決めてください。",

        // Ask Kibi
        "AI guess": "AI の推測",
        "Double-check before acting.": "実行の前にご自身でも確かめてください。",
        "Not confident. Contents:": "確信が持てません。中身は次のとおりです:",
        "Analyzing": "解析中",
        "Explain": "解析",
        "Explain is ready. Click the sparkle on an unrecognized folder in the Map.": "解析機能は使えます。マップで未分類フォルダのアイコンを押してください。",
        "Explain appears once Apple Intelligence is on in System Settings.": "システム設定で Apple Intelligence をオンにすると、解析機能が使えます。",
        // Chrome
        "Overview": "概要",
        "Map": "マップ",
        "Items": "項目",
        "History": "履歴",
        "Copied": "コピーしました",
        "Copy Command": "コマンドをコピー",
        "Show me": "見せて",
        "Reveal in Finder": "Finder に表示",
        "What is this?": "これは何?",
        "Elbowroom has returned %@ to this Mac": "Elbowroom はこの Mac に %@ を返してきました",
        "one square is about %@ at this zoom": "このズームでは 1 マスが約 %@",
        "+ %1$d smaller · %2$@": "+ 小さいもの %1$d 件 · %2$@",
        "Checking what changed": "変化を確認中",
        "This week": "今週",
        "Expand access": "アクセスを広げる",
        "Search": "検索",
        "Scan again": "もう一度スキャン",
        "Settings": "設定",
        "Inside %@": "%@ の中",
        "Everything else": "そのほかすべて",
        "Your files and apps": "あなたのファイルとアプリ",
        "Files too small to draw one by one.": "1 つずつ描くには小さすぎるファイルです。",
        "Smaller items, one pile.": "小さいものをひとまとめに。",
        "Back to the whole disk": "ディスク全体に戻る",
        "Return key opens": "Return キーで開く",
        "Offloaded. Size counts on the drive.": "オフロード済み。容量はドライブ側で数えます。",
        "Freed through the owning app, not by Elbowroom directly.": "Elbowroom が直接ではなく、持ち主のアプリを通して空ける分です。",
        "Hide for 30 days": "30 日間隠す",
        "Test-run simulator clones": "テスト実行用シミュレータの複製",
        "Copies xcodebuild makes for parallel testing. Tests remake them when needed.": "並列テストのために xcodebuild が作る複製です。必要になればテストが作り直します。",
        "Select all caches": "キャッシュをすべて選択",
        "Select stale > 90 days": "90 日以上未使用を選択",
        "Clear filter": "絞り込みを解除",
        "%d item": "%d 件",
        "%d items": "%d 件",
        "Name": "名前",
        "Size": "サイズ",
        "Tier": "安全度",
        "Owner": "持ち主",
        "Last touched": "最終使用",
        "Put Back": "元に戻す",
        "Export CSV": "CSV を書き出す",
        "Room to build.": "つくる余白を。",

        // Staleness
        "touched today": "今日使いました",
        "untouched %d day": "%d 日 未使用",
        "untouched %d days": "%d 日 未使用",
        "untouched %d weeks": "%d 週間 未使用",
        "untouched %d month": "%dか月 未使用",
        "untouched %d months": "%dか月 未使用",
        "untouched %d year": "%d 年 未使用",
        "untouched %d years": "%d 年 未使用",
        "today": "今日",
        "yesterday": "昨日",
        "%d days ago": "%d 日前",
        "%d weeks ago": "%d 週間前",
        "%d months ago": "%dか月前",
        "%d years ago": "%d 年前",

        // Atlas identities
        "Xcode build products": "Xcode のビルド生成物",
        "Intermediate build files. Xcode remakes them on the next build.": "ビルドの中間ファイルです。次のビルドで Xcode が作り直します。",
        "Xcode archives": "Xcode のアーカイブ",
        "Past app builds and their debug symbols. Keep them if you shipped those builds.": "過去のアプリビルドとデバッグシンボルです。配布したビルドなら残しておきましょう。",
        "Device support files": "実機サポートファイル",
        "Debug files copied from each iPhone or iPad you plugged in. They copy over again on the next connection.": "接続した iPhone や iPad からコピーされたデバッグ用ファイルです。次に接続すればまたコピーされます。",
        "Simulator devices": "シミュレータのデバイス",
        "The simulated iPhones and iPads Xcode created, with their apps and data.": "Xcode が作った仮想の iPhone や iPad と、その中のアプリとデータです。",
        "Simulator runtimes": "シミュレータのランタイム",
        "Re-downloadable OS images for the simulator. Xcode's own panel removes them safely.": "再ダウンロードできるシミュレータ用 OS イメージです。Xcode 自身の画面から安全に削除できます。",
        "Simulator caches": "シミュレータのキャッシュ",
        "Scratch files the simulator refills as it runs.": "シミュレータが動きながら作り直す作業ファイルです。",
        "Swift package caches": "Swift パッケージキャッシュ",
        "Downloaded package sources. They download again when a build needs them.": "ダウンロード済みのパッケージソースです。ビルドが必要とすれば再ダウンロードされます。",
        "Swift package build folder": "Swift パッケージのビルドフォルダ",
        "Build output for a Swift package. The next build remakes it.": "Swift パッケージのビルド出力です。次のビルドで作り直されます。",
        "SwiftUI preview data": "SwiftUI プレビューのデータ",
        "Simulators and caches used by Xcode previews. They rebuild on the next preview.": "Xcode プレビューが使うシミュレータとキャッシュです。次のプレビューで作り直されます。",
        "Xcode caches": "Xcode のキャッシュ",
        "Scratch files Xcode refills as it runs.": "Xcode が動きながら作り直す作業ファイルです。",
        "JavaScript packages": "JavaScript パッケージ",
        "Installed packages for one project. The next install remakes the folder.": "このプロジェクトにインストールされたパッケージです。次のインストールでフォルダごと作り直されます。",
        "npm cache": "npm キャッシュ",
        "Downloaded package archives. npm refills this as you install.": "ダウンロード済みのパッケージアーカイブです。インストールのたびに npm が補充します。",
        "pnpm store": "pnpm ストア",
        "The shared package store pnpm links projects to. It refills on install.": "pnpm が各プロジェクトへリンクする共有ストアです。インストール時に補充されます。",
        "Yarn cache": "Yarn キャッシュ",
        "Downloaded package archives. Yarn refills this as you install.": "ダウンロード済みのパッケージアーカイブです。インストールのたびに Yarn が補充します。",
        "Bun cache": "Bun キャッシュ",
        "Downloaded package archives. Bun refills this as you install.": "ダウンロード済みのパッケージアーカイブです。インストールのたびに Bun が補充します。",
        "Rust build folder": "Rust のビルドフォルダ",
        "Compiled output for one project. The next cargo build remakes it.": "このプロジェクトのコンパイル結果です。次の cargo build で作り直されます。",
        "Cargo registry": "Cargo レジストリ",
        "Downloaded crate sources shared by your Rust projects. Cargo refills it on the next fetch.": "Rust プロジェクトが共有するクレートのソースです。次の取得時に Cargo が補充します。",
        "Cargo git checkouts": "Cargo の git チェックアウト",
        "Git dependencies cargo cloned. They clone again when needed.": "cargo がクローンした git 依存です。必要になればまたクローンされます。",
        "Homebrew downloads": "Homebrew のダウンロード",
        "Installer archives Homebrew already used. It downloads fresh ones when needed.": "Homebrew が使い終えたインストーラです。必要になれば新しく取得します。",
        "Homebrew old versions": "Homebrew の古いバージョン",
        "Older versions kept beside the current ones. brew cleanup removes them safely.": "現行版のとなりに残った古いバージョンです。brew cleanup が安全に片づけます。",
        "Docker Desktop data": "Docker Desktop のデータ",
        "Docker's virtual disk with your images, containers, and volumes.": "イメージ、コンテナ、ボリュームが入った Docker の仮想ディスクです。",
        "OrbStack data": "OrbStack のデータ",
        "OrbStack's virtual disk with your machines, images, and volumes.": "マシン、イメージ、ボリュームが入った OrbStack の仮想ディスクです。",
        "iPhone and iPad backups": "iPhone と iPad のバックアップ",
        "Full device backups Finder made. Finder's own panel manages them.": "Finder が作ったデバイスの完全バックアップです。Finder 自身の画面で管理します。",
        "Trash": "ゴミ箱",
        "Files you already deleted. Emptying the Trash frees them for good.": "すでに削除したファイルです。ゴミ箱を空にすれば完全に片づきます。",
        "App cache": "アプリのキャッシュ",
        "Scratch files this app refills as it runs.": "このアプリが動きながら作り直す作業ファイルです。",
        "Purgeable space": "パージ可能な領域",
        "Local Time Machine snapshots": "ローカル Time Machine スナップショット",
        "Hugging Face models": "Hugging Face モデル",
        "Downloaded model weights. They download again on the next use.": "ダウンロード済みのモデルです。次に使うときにまたダウンロードされます。",
        "Ollama models": "Ollama モデル",
        "Downloaded model weights. ollama pull brings any of them back.": "ダウンロード済みのモデルです。ollama pull でいつでも戻せます。",
        "LM Studio models": "LM Studio モデル",

        // Teach flows
        "Simulator runtimes and devices": "シミュレータのランタイムとデバイス",
        "Xcode owns these. Its own panel removes them safely and can download them again later.": "これは Xcode の持ちものです。Xcode 自身の画面から安全に削除でき、あとで再ダウンロードもできます。",
        "Open Xcode's Components panel": "Xcode の Components 画面を開く",
        "List the installed runtimes, then delete one by its id.": "インストール済みランタイムを一覧し、id を指定して削除します。",
        "Docker owns this virtual disk. Removing files inside it by hand corrupts it.": "この仮想ディスクは Docker の持ちものです。中のファイルを手で消すと壊れます。",
        "Open Docker Desktop": "Docker Desktop を開く",
        "Removes stopped containers, unused networks, and all unused images.": "停止中のコンテナ、未使用のネットワーク、未使用のイメージをすべて削除します。",
        "Prune deletes every image no container is using. Pulling them back takes time and bandwidth.": "prune はどのコンテナも使っていないイメージをすべて削除します。取り直すには時間と通信量がかかります。",
        "OrbStack owns this virtual disk. Its own settings reclaim space safely.": "この仮想ディスクは OrbStack の持ちものです。OrbStack の設定から安全に空けられます。",
        "Open OrbStack": "OrbStack を開く",
        "Prune deletes every image no container is using.": "prune はどのコンテナも使っていないイメージをすべて削除します。",
        "Asks macOS to thin snapshots until about 20 GB frees up.": "約 20 GB 空くまでスナップショットを間引くよう macOS に頼みます。",
        "Finder owns these backups. Its own panel shows each one and deletes them safely.": "バックアップは Finder の持ちものです。Finder の画面で 1 つずつ確認して安全に削除できます。",
        "Open Finder's backup list": "Finder のバックアップ一覧を開く",
        "You already deleted these files. Emptying the Trash frees them for good.": "すでに削除したファイルです。ゴミ箱を空にすれば完全に片づきます。",
        "Open the Trash": "ゴミ箱を開く",
        "Time Machine": "Time Machine",
        "Time Machine owns this. Its settings control what it keeps.": "これは Time Machine の持ちものです。何を残すかは Time Machine の設定で決まります。",
        "Open Time Machine settings": "Time Machine の設定を開く",
        "Homebrew owns the Cellar. brew cleanup removes old versions safely and keeps what is linked.": "Cellar は Homebrew の持ちものです。brew cleanup が古いバージョンを安全に削除し、リンク中のものは残します。",
        "Removes old versions and stale downloads of everything installed.": "インストール済みのものの古いバージョンと古いダウンロードを削除します。",

        // Settings
        "General": "一般",
        "Receipts": "控え",
        "Privacy": "プライバシー",
        "Play sounds": "サウンドを鳴らす",
        "Low-space alert": "空き容量の警告",
        "%d GB free": "空き %d GB",
        "Connection speed": "回線速度",
        "Measure Again": "もう一度計測",
        "The connection speed only phrases re-download times. Nothing uploads.": "回線速度は再ダウンロード時間の表現にだけ使います。何も送信されません。",
        "Language": "言語",
        "System": "システムに合わせる",
        "Takes effect after Elbowroom reopens.": "Elbowroom を開き直すと反映されます。",
        "Verify every byte after copies": "コピー後にすべてのバイトを検証",
        "Sampled verification is the default; full verification reads the whole copy back.": "通常は抜き取り検証です。完全検証はコピー全体を読み直します。",
        "Open the Stash catalog": "Stash の一覧を開く",
        "Stash drive": "Stash ドライブ",
        "Stashed": "保管中",
        "Entries": "項目数",
        "Share anonymous usage statistics": "匿名の利用統計を送る",
        "Aggregates only: event names, byte counts, durations. No paths, no file names, no device fingerprint. Stored locally where you can read them.": "集計のみ: イベント名、バイト数、所要時間。パスもファイル名も端末の指紋も含みません。手元で読める場所に保存されます。",
        "Show the local analytics file": "ローカルの統計ファイルを表示",
        "and %d more": "ほか %d 件",
        "in Trash": "ゴミ箱に",
        "emptied": "空にした",
        "restored": "戻した",
        "deleted": "削除済み",
        "1.0": "1.0",
        "grew": "増加",
        "freed": "解放",
    ]
}
