import Foundation

/// Ja-JP. Keys are the English copy-deck strings. Plain, warm Japanese in
/// the same register as the English: no alarm, no marketing, no em-dashes,
/// no exclamation points. Kibi's short lines are re-authored, not translated.
/// Drafted for native review before store submission.
extension Loc {
    static let jaStrings: [String: String] = [
        "View all items": "すべての項目を表示",
        "Your apps can recreate these files.": "アプリが再生成できるファイルです。",
        "Your tools can rebuild these files.": "ツールが再生成できるファイルです。",
        "Managed by macOS.": "macOS が管理します。",
        "App data kept in several places.": "複数の場所に保存されたアプリデータです。",
        "%d location": "%d か所",
        "%d locations": "%d か所",
        "Hide details": "詳細を非表示",
        "%d group": "%d グループ",
        "%d groups": "%d グループ",
        "%@ total": "合計 %@",
        "Review cleanup": "削除内容を確認",
        "Show details": "詳細を表示",
        "Expanded": "展開中",
        "Collapsed": "折りたたみ中",
        "Review %@ of files your apps can recreate.": "アプリが再生成できる %@ のファイルを確認します。",
        "Build files from projects unchanged for at least 30 days. Your source files stay.": "30 日以上変更のないプロジェクトのビルドファイルです。ソースファイルは残ります。",
        "App and download caches": "アプリとダウンロードのキャッシュ",
        "Files your apps can fetch or create again.": "アプリが再取得または再生成できるファイルです。",
        "Build files": "ビルドファイル",
        "Generated files your development tools can rebuild.": "開発ツールが再生成できるファイルです。",
        "Downloaded models": "ダウンロード済みモデル",
        "Models for local AI features. Removing them means downloading them again.": "ローカル AI 機能のモデルです。削除すると再ダウンロードが必要になります。",
        "App-managed storage": "アプリ管理のストレージ",
        "Backups, virtual disks and app data. Each app has its own cleanup options.": "バックアップ、仮想ディスク、アプリデータです。アプリごとに削除方法が異なります。",
        "Developer tools": "開発ツール",
        "Installed tools and extensions. Keep the ones your projects use.": "インストール済みのツールと拡張機能です。プロジェクトで使うものは残してください。",
        "Your apps": "アプリ",
        "Apps and the data they keep. Review both before uninstalling.": "アプリと保存データです。アンインストールする前に両方を確認してください。",
        "Files and history": "ファイルと履歴",
        "Your projects, libraries and saved work. Review individually.": "プロジェクト、ライブラリ、保存した作業です。個別に確認してください。",
        "macOS and services": "macOS とサービス",
        "System files and background services, explained without a cleanup recommendation.": "システムファイルとバックグラウンドサービスです。削除を勧めずに内容を説明します。",
        "Temporary files this app can recreate. Close the app before cleanup; your documents and account data stay.": "アプリが再生成できる一時ファイルです。削除する前にアプリを終了してください。書類とアカウントデータは残ります。",
        "Tool runtimes": "ツールの実行環境",
        "Installed dependencies used to run your tools. Keep active versions; their location does not make them disposable caches.": "ツールの実行に必要な依存関係です。使用中のバージョンは残してください。保存場所だけで削除可能なキャッシュとは判断できません。",
        "Python installations": "Python のインストール",
        "Python versions your projects may depend on. Remove a version only after checking which environments use it.": "プロジェクトが依存している可能性のある Python です。使用している環境を確認してから削除してください。",
        "Editor extensions": "エディタの拡張機能",
        "Installed editor features. Uninstall extensions in the editor so its settings stay consistent.": "インストール済みのエディタ機能です。設定の整合性を保つため、エディタ内でアンインストールしてください。",
        "Assistant work and history": "アシスタントの作業と履歴",
        "Saved conversations, task files, plugins and settings. These can include work you cannot recreate; review them individually.": "保存した会話、タスクファイル、プラグイン、設定です。再生成できない作業が含まれる場合があるため、個別に確認してください。",
        "Search indexes": "検索インデックス",
        "Indexes macOS uses to find your content. They are separate from your original files and managed by the system.": "macOS がコンテンツを検索するためのインデックスです。元のファイルとは別で、システムが管理します。",
        "Wallpaper downloads": "壁紙のダウンロード",
        "Desktop backgrounds downloaded by macOS. The system manages these assets.": "macOS がダウンロードしたデスクトップの背景です。システムが管理します。",
        "Intelligence and suggestions": "インテリジェンスと提案",
        "Data used by macOS background intelligence and suggestion services. This is system-managed storage.": "macOS のバックグラウンドインテリジェンスと提案機能が使うデータです。システムが管理します。",
        "Background services": "バックグラウンドサービス",
        "Data and compiled models kept by system services. The system controls their lifecycle.": "システムサービスが保持するデータとコンパイル済みモデルです。システムが管理します。",
        "Shared app data": "共有アプリデータ",
        "Support files and shared containers not already counted with an app. They may contain documents and settings; recognition is not a deletion recommendation.": "アプリにまだ計上されていないサポートファイルと共有コンテナです。書類や設定を含む場合があり、分類されたからといって削除を勧めるものではありません。",
        "Installed packages": "インストール済みパッケージ",
        "Command-line tools and their dependencies. Use the package manager to remove software your projects no longer need.": "コマンドラインツールと依存関係です。プロジェクトで不要になったソフトウェアはパッケージマネージャーで削除してください。",
        "Command Line Tools": "コマンドラインツール",
        "Installed compilers and SDKs used by development tools. These are software installations, not project build files.": "開発ツールが使うコンパイラと SDK です。プロジェクトのビルドファイルではなく、インストール済みのソフトウェアです。",
        "System diagnostics": "システム診断",
        "Logs and diagnostic databases maintained by macOS. The system manages their retention.": "macOSが管理するログと診断データベースです。保存期間はシステムが管理します。",
        "System temporary files": "システム一時ファイル",
        "Working files and caches used by macOS and apps. Some are in use; the system manages cleanup.": "macOSとアプリが使用する作業ファイルとキャッシュです。使用中のものもあり、削除はシステムが管理します。",
        "Downloaded system assets": "ダウンロード済みシステム素材",
        "Speech, language and other resources downloaded for macOS features. The system manages these downloads.": "macOSの機能に必要な音声や言語などのリソースです。ダウンロードはシステムが管理します。",
        "System databases": "システムデータベース",
        "Settings, service records and other databases used by macOS. Keep these files in place.": "macOSの設定やサービス記録などのデータベースです。そのまま保持してください。",
        "Document versions": "書類のバージョン",
        "Previous versions of documents kept by macOS. These may be needed to recover earlier work.": "macOSが保存した書類の以前のバージョンです。過去の作業を復元するために必要な場合があります。",
        "Project source and files": "プロジェクトのソースとファイル",
        "Source code and working files in detected projects, excluding separately listed builds and review items. Keep work you still need.": "検出されたプロジェクトのソースコードと作業ファイルです。別に表示されるビルドや確認対象は含みません。必要な作業は保持してください。",
        "Documents and desktop files": "書類とデスクトップのファイル",
        "Files in Documents and Desktop, excluding items already listed separately. These are personal files to review before deleting.": "書類とデスクトップのファイルです。別に表示される項目は含みません。削除する前に内容を確認してください。",
        "Downloaded files": "ダウンロードしたファイル",
        "Files in Downloads, excluding installers and other items already listed separately. Review which downloads you still need.": "ダウンロード内のファイルです。別に表示されるインストーラなどは含みません。必要なファイルを確認してください。",
        "Photos, music and video files": "写真、音楽、動画ファイル",
        "Photos, music and videos, excluding libraries and items already listed separately. These may be your only copies.": "写真、音楽、動画ファイルです。別に表示されるライブラリなどは含みません。唯一のコピーかもしれません。",
        "Python environments": "Python環境",
        "Python installations and packages used by individual projects. Keep environments needed by active work.": "個々のプロジェクトで使用するPythonとパッケージです。作業に必要な環境は保持してください。",
        "Automation runner files": "自動化ランナーのファイル",
        "Installed automation tools, updates and job files. These can include active jobs and credentials; they are not disposable caches.": "自動化ツール、更新、ジョブのファイルです。実行中のジョブや認証情報を含む場合があり、削除可能なキャッシュではありません。",
        "Downloaded iCloud files": "ダウンロード済みiCloudファイル",
        "Local copies of iCloud documents. Deleting a document can delete it from iCloud and your other devices too.": "iCloud書類のローカルコピーです。書類を削除すると、iCloudや他のデバイスからも削除される場合があります。",
        "Developer support files": "開発サポートファイル",
        "Installed developer resources not already listed with a tool or project. Keep resources your development tools still use.": "ツールやプロジェクトに別途表示されない開発用リソースです。開発ツールが使用するものは保持してください。",
        "Application components": "アプリケーション構成ファイル",
        "Installed application files not already counted with an app. These can include shared components and supporting tools.": "アプリにまだ計上されていないインストール済みファイルです。共有コンポーネントや補助ツールを含む場合があります。",
        "APFS container allocation": "APFSコンテナの割り当て",
        "Space used by the disk container outside the reported volume allocations. This is not a collection of files to delete.": "報告されたボリューム割り当ての外側でディスクコンテナが使用する領域です。削除できるファイルの集まりではありません。",
        "%@ in scanned files · %@ not matched to readable files": "スキャン済みファイル %@・読み取り可能なファイルに対応しない領域 %@",
        "Scanned files still need useful groups. The unmatched balance can include protected locations and filesystem accounting differences; it is not a cleanup estimate.": "スキャン済みファイルには、まだ分類が必要なものがあります。対応しない領域には、保護された場所やファイルシステムの計算上の差が含まれる可能性があり、削除可能な容量の見積もりではありません。",
        "Software update files": "ソフトウェアアップデートファイル",
        "Downloaded macOS update files. Software Update manages installation and cleanup.": "ダウンロードされた macOS アップデートファイルです。ソフトウェアアップデートがインストールと削除を管理します。",
        "Boot support": "起動サポート",
        "Files macOS needs to start up. This is not an estimate of space an update will free.": "macOS の起動に必要なファイルです。アップデートで空く容量の見積もりではありません。",
        "The app and its retained data. Caches the app can recreate are listed separately for cleanup.": "アプリと保持されるデータです。再生成できるキャッシュは削除用に別途表示されます。",
        "Some space still needs an explanation. Explore the map for a closer look.": "まだ説明が必要な容量があります。マップで詳しく確認できます。",

        "pip cache": "pip キャッシュ",
        "Python packages downloaded or built by pip. Removing the cache leaves installed packages in place; future installs may download and build them again.": "pip がダウンロードまたはビルドした Python パッケージです。削除してもインストール済みのパッケージは残ります。次回のインストール時に再ダウンロードや再ビルドが必要になる場合があります。",
        "Gradle caches": "Gradle キャッシュ",
        "Downloaded dependencies and generated build files. Gradle downloads or rebuilds them when needed. Close Gradle builds before removing them.": "ダウンロードした依存関係と生成されたビルドファイルです。必要に応じて Gradle が再取得または再生成します。削除する前に Gradle のビルドを終了してください。",
        "Music library": "ミュージックライブラリ",
        "Music library metadata and playlists. Your music files may live elsewhere; this is personal library data, not a disposable cache.": "ミュージックのライブラリ情報とプレイリストです。音楽ファイルは別の場所にある場合があります。削除可能なキャッシュではなく、個人のライブラリデータです。",
        "TV library": "TV ライブラリ",
        "TV library metadata and organization. Downloaded videos may live elsewhere; review your library in TV before changing it.": "TV のライブラリ情報と整理データです。ダウンロードした動画は別の場所にある場合があります。変更する前に TV でライブラリを確認してください。",
        "Video editing library": "動画編集ライブラリ",
        "Video projects, source media, and generated files kept together. Some media may live elsewhere. Review the library in its editing app; it can contain your only originals.": "動画プロジェクト、素材、生成ファイルをまとめたライブラリです。一部の素材は別の場所にある場合があります。唯一のオリジナルが含まれる可能性があるため、編集アプリで確認してください。",
        "Aperture library": "Aperture ライブラリ",
        "Photo originals and edits from Aperture. Keep this library until you have verified that its photos are preserved elsewhere.": "Aperture の写真のオリジナルと編集内容です。写真が別の場所に保存されていることを確認するまで、このライブラリを保管してください。",

        "Open Docker Desktop to see what can be cleaned up. Elbowroom will refresh this list when Docker is ready.": "Docker Desktop を開くと、削除できる項目を確認できます。Docker の準備ができると、Elbowroom がこの一覧を更新します。",
        "Waiting for Docker Desktop to be ready.": "Docker Desktop の準備を待っています。",
        "Docker is not ready yet. Finish any setup in Docker Desktop, then try again.": "Docker の準備がまだできていません。Docker Desktop で必要な設定を完了してから、もう一度お試しください。",
        "Could not open Docker Desktop": "Docker Desktop を開けませんでした",
        "Check that Docker Desktop is installed and can open on this Mac.": "Docker Desktop がインストールされ、この Mac で開けることを確認してください。",
        "macOS may ask for administrator approval to move this app to Trash. Elbowroom continues after approval.": "このアプリをゴミ箱に移すため、macOS が管理者の承認を求める場合があります。承認後、Elbowroom が処理を続けます。",
        "Review and try again": "確認して再試行",
        // 11.1 Onboarding
        "Most of what fills a developer's disk is caches and build output.": "開発者のディスクを埋めているのは、大部分がキャッシュとビルド生成物です。",
        "Continue": "続ける",
        "Local processing": "この Mac の中だけで処理します",
        "Scanning, explanations, and AI answers all run on this Mac. Elbowroom does not touch the network while it scans. Usage statistics are anonymous, optional, and off by default.": "スキャンも説明も AI の回答も、すべてこの Mac の上で動きます。スキャン中に Elbowroom がネットワークに触れることはありません。利用統計は匿名かつ任意で、初期設定ではオフです。",
        "Let Elbowroom see the whole disk": "Elbowroom にディスク全体を見せてください",
        "One switch in System Settings lets Elbowroom count everything, with no permission pop-ups during the scan. What it reads never leaves this Mac.": "システム設定のスイッチ 1 つで、Elbowroom がすべてを数えられるようになります。スキャン中に許可のポップアップは出ません。読み取った内容がこの Mac の外に出ることはありません。",
        "Start the scan": "スキャンを開始",
        "Full Disk Access is already on.": "フルディスクアクセスはすでにオンです。",
        "Start with just my home folder": "まずホームフォルダだけで始める",
        "Waiting for the switch": "スイッチを待っています",
        "macOS may ask to quit and reopen Elbowroom. Let it: the scan starts right where you left off.": "macOS が Elbowroom の再起動を求めることがあります。そのまま任せてください。スキャンは続きから始まります。",
        "Relaunch Elbowroom": "Elbowroom を再起動",
        "Drag the Elbowroom icon above into the list, then turn it on.": "上の Elbowroom アイコンをリストにドラッグして、スイッチをオンにしてください。",
        "A few folders need your OK": "いくつかのフォルダに許可が必要です",
        "macOS asks before Elbowroom can look inside these. Allow each one and nothing goes missing from the count.": "Elbowroom がこれらの中を見る前に、macOS が確認します。それぞれ許可すると、数え漏れがなくなります。",
        "Elbowroom won't see files outside your home folder.": "ホームフォルダの外にあるファイルは Elbowroom から見えません。",
        "Not visible for now": "今は見えません",
        "Desktop": "デスクトップ",
        "Documents": "書類",
        "Downloads": "ダウンロード",
        "Photos library": "写真ライブラリ",
        "Other apps' data": "ほかのアプリのデータ",
        "You can safely get back": "今日、安全に取り戻せるのは",
        "today.": "です。",
        "Every item is identified and rated for safety.": "すべての項目が識別され、安全度が付いています。",
        "Low on space. Elbowroom picked the quickest safe items first.": "空きが少なくなっています。すぐ効く安全な項目から選んであります。",
        "Not much to reclaim right now. Elbowroom will watch for growth.": "今は取り戻せるものが多くありません。増えたら Elbowroom が気づきます。",
        "Reclaim now": "今すぐ取り戻す",
        "Open the map": "マップを開く",
        "Free up %@ in about a minute": "約 1 分で %@ を空ける",
        "Some areas weren't visible. Expand access": "見えない場所がありました。アクセスを広げる",

        "The quickest safe items, pre-checked.": "すぐ効く安全な項目に、チェックを入れてあります。",
        "A plan you approve first.": "実行の前に、あなたが計画を確認します。",
        "A treemap of the whole disk.": "ディスク全体のツリーマップ。",

        // 11.2 Ticker
        "Found %@ of Xcode build products": "Xcode のビルド生成物 %@ を発見",
        "%1$@ of simulator devices, unused since %2$@": "シミュレータのデバイス %1$@(%2$@から未使用)",
        "%@ of Rust build folders. Your next build remakes these.": "Rust のビルドフォルダ %@。次のビルドで作り直されます。",
        "%@ of package caches. These download again when needed.": "パッケージキャッシュ %@。必要になれば再ダウンロードされます。",
        "%1$@ in iPhone backups from %2$@": "%2$@の iPhone バックアップに %1$@",
        "Snapshots hold %@. macOS thins them on its own.": "スナップショットが %@ を保持。macOS が自動で間引きます。",
        "Large disk. This can take a few minutes.": "大きなディスクです。数分かかることがあります。",
        "%@ of JavaScript packages. These install again when needed.": "JavaScript パッケージ %@。必要になれば再インストールされます。",
        "Found %2$@ of %1$@": "%1$@ %2$@ を発見",

        // 11.3 Tiers
        "Deleted safely. It is re-created on demand.": "安全に削除できます。必要になれば自動で再生成されます。",
        "Rebuilt from your project by its own tools.": "プロジェクトのツールが次回のビルドで再生成します。",
        "Owned by another app. Elbowroom opens that app's controls.": "他のアプリの管理領域です。Elbowroom はそのアプリの設定画面を開きます。",
        "Your files. Elbowroom never suggests changes here.": "あなたのファイルです。Elbowroom が変更を提案することはありません。",
        "Cache": "キャッシュ",
        "Derived": "生成物",
        "App-managed": "アプリ管理",
        "Personal": "個人ファイル",
        // 11.4 Reclaim
        "Reclaim plan": "取り戻す計画",
        "The next %1$@ run downloads about %2$@ again (%3$@ on your connection)": "次に %1$@ を実行すると約 %2$@ を再ダウンロードします(お使いの回線で %3$@)",
        "Keep in Trash for 7 days": "7 日間ゴミ箱に残す",
        "Keep reclaimed items in the Trash for 7 days": "取り除いた項目を 7 日間ゴミ箱に残す",
        "When off, a reclaim deletes items immediately. Each plan can change this for one run.": "オフにすると、取り除いた項目はすぐに削除されます。実行ごとにプランで変更もできます。",
        "Trash first": "まずゴミ箱へ",
        "Deleting %@ needs one more switch": "%@ を削除するには、もう 1 つのスイッチが必要です",
        "macOS keeps a separate switch for deleting other apps, called App Management. Full Disk Access does not cover it. Turn Elbowroom on there and this uninstall continues on its own.": "macOS は他のアプリの削除に「アプリ管理」という別のスイッチを設けています。フルディスクアクセスには含まれません。そこで Elbowroom をオンにすると、このアンインストールは自動で続行されます。",
        "Open App Management settings": "アプリ管理の設定を開く",
        "macOS applies this switch when Elbowroom reopens. Quit and reopen, and the uninstall picks up where it left off.": "このスイッチは Elbowroom を開き直したときに反映されます。終了して開き直すと、アンインストールは続きから再開します。",
        "Reclaimed items move to a dated folder in the Trash and stay for 7 days. A receipt records every move and can put anything back. Turning this off deletes immediately instead.": "取り除いた項目は日付付きフォルダとしてゴミ箱に移り、7 日間残ります。すべての移動はレシートに記録され、いつでも元に戻せます。オフにすると、ゴミ箱に入らずすぐに削除されます。",
        "Reclaim %@": "%@ を取り戻す",
        "%@ reclaimed. Receipt saved.": "%@ を取り戻しました。控えを保存しました。",
        "Elbowroom skipped %d item:": "%d 件をスキップしました:",
        "Elbowroom skipped %d items:": "%d 件をスキップしました:",
        "Rebuilding this next time takes about %@.": "次に作り直すときは約 %@ かかります。",
        "OK": "OK",
        "Cancel": "キャンセル",
        "%@ safely reclaimable": "%@ を安全に取り戻せます",
        "safely reclaimable": "安全に取り戻せます",
        "%1$d item · %2$@": "%1$d 件 · %2$@",
        "%1$d items · %2$@": "%1$d 件 · %2$@",
        "Reclaim": "取り戻す",
        "Clear": "解除",
        "Stopped. %d item was already reclaimed and stays reclaimed.": "中断しました。%d 件はすでに取り戻し済みで、そのままです。",
        "Stopped. %d items were already reclaimed and stay reclaimed.": "中断しました。%d 件はすでに取り戻し済みで、そのままです。",

        "%@ is running. Quit it first.": "%@ が起動中です。先に終了してください。",
        "Clean Up": "クリーンアップ",
        "Asking the tool what can go": "削除できるものをツールに確認中",
        "Elbowroom will run:": "Elbowroom は次を実行します:",
        "Run (%@)": "実行 (%@)",
        "These delete through the tool itself, not the Trash. Put Back does not apply.": "これらはツール自体を通じて削除され、ゴミ箱には入りません。「元に戻す」は使えません。",
        "The tool for this is not installed.": "このためのツールがインストールされていません。",
        "The tool did not answer in time.": "ツールが時間内に応答しませんでした。",
        "Start the container app first.": "先にコンテナアプリを起動してください。",
        "%d unavailable simulators": "利用できないシミュレータ %d 台",
        "Their runtimes are gone. Xcode cannot boot them again.": "ランタイムが削除済みのため、Xcode はもう起動できません。",
        "never booted": "一度も起動していません",
        "superseded by %@": "%@ に置き換えられました",
        "Stopped containers": "停止中のコンテナ",
        "Exited containers and their writable layers.": "終了したコンテナとその書き込みレイヤー。",
        "Unused images": "未使用のイメージ",
        "Images no container is using.": "どのコンテナも使っていないイメージ。",
        "Pulling them back takes time and bandwidth.": "取り直すには時間と帯域がかかります。",
        "Build cache": "ビルドキャッシュ",
        "Layers docker build keeps for reuse.": "docker build が再利用のために保持するレイヤー。",
        "Unused volumes": "未使用のボリューム",
        "Volumes no container references.": "どのコンテナからも参照されていないボリューム。",
        "Volumes can hold data you created. Check this only if you are sure.": "ボリュームにはあなたが作成したデータが入っていることがあります。確実な場合のみチェックしてください。",
        "%1$@ (%2$@) is current and stays.": "%1$@（%2$@）は最新のため残ります。",
        "The current runtime. Simulators stop working until you add it back.": "現在のランタイムです。戻すまでシミュレータは動きません。",
        "%d devices used recently stay.": "最近使った %d 台のデバイスは残ります。",
        "Old versions and stale downloads": "古いバージョンと古いダウンロード",
        "brew cleanup keeps what is linked and removes the rest.": "brew cleanup はリンク中のものを残し、それ以外を削除します。",
        // Time Machine local snapshots
        "Local safety snapshots": "ローカルの安全スナップショット",
        "made %@": "作成: %@",
        "These are this Mac's local restore points. The next backup runs longer while Time Machine takes fresh ones.": "これはこの Mac のローカル復元ポイントです。次のバックアップは、Time Machine が新しいスナップショットを作り直すぶん長くかかります。",
        "Your backup history on '%@' is separate and stays untouched.": "「%@」にあるバックアップ履歴は別物で、ここでは一切触れません。",
        "No backup destination is set up, so these snapshots are this Mac's only file history. Deleting them removes the way back to recent versions.": "バックアップ先が設定されていないため、これらのスナップショットがこの Mac の唯一のファイル履歴です。削除すると、最近のバージョンへ戻る手段がなくなります。",
        "Up to %@ comes back. Elbowroom measures the exact amount after the run.": "最大 %@ が戻ります。正確な量は実行後に Elbowroom が測定します。",
        "A backup is running right now. Try again after it finishes.": "いまバックアップが実行中です。終わってからもう一度どうぞ。",
        "%d update snapshot stays. The macOS updater owns it and clears it when the update finishes.": "%d 個のアップデート用スナップショットは残ります。macOS のアップデータが所有し、アップデート完了時に自動で消します。",
        "%d update snapshots stay. The macOS updater owns them and clears them when the update finishes.": "%d 個のアップデート用スナップショットは残ります。macOS のアップデータが所有し、アップデート完了時に自動で消します。",
        "Trim these automatically": "自動で間引く",
        "macOS has no off switch for local snapshots. When new ones appear, Elbowroom deletes them once the backup finishes. Backups start fresh and can run longer.": "macOS にはローカルスナップショットを止めるスイッチがありません。新しいものが現れたら、バックアップ完了後に Elbowroom が削除します。バックアップは毎回まっさらから始まり、時間が長くかかることがあります。",
        "Deleted %d local snapshot": "%d 個のローカルスナップショットを削除しました",
        "Deleted %d local snapshots": "%d 個のローカルスナップショットを削除しました",
        "Run (up to %@)": "実行 (最大 %@)",
        // Apps and System tiers
        "Installed applications and the data they keep. Uninstalling asks about both.": "インストール済みのアプリと、アプリが保存しているデータ。アンインストール時にどちらも確認します。",
        "macOS itself. Elbowroom explains it and names the lever when one exists.": "macOS そのものです。Elbowroom は説明し、打てる手があるときはその名前を示します。",
        "Apps": "アプリ",
        "System": "システム",
        "Uninstall": "アンインストール",
        "Uninstall %@": "%@ をアンインストール",
        "The app itself, with everything it keeps in your Library counted beside it.": "アプリ本体と、ライブラリに保存しているすべてを合わせて数えています。",
        "Settings, caches, and documents this app kept in your Library.": "このアプリがライブラリに残した設定、キャッシュ、書類。",
        "The operating system itself, sealed and signed. Updates replace it in place.": "オペレーティングシステムそのもの。封印・署名されており、アップデートがその場で置き換えます。",
        "Space macOS reserves to prepare its next update. Installing the update returns most of it.": "macOS が次のアップデートの準備のために確保している領域。アップデートをインストールすると大部分が戻ります。",
        "Memory that spilled to disk. A restart drains it, and it grows back under load.": "ディスクにあふれたメモリ。再起動で空になり、負荷がかかるとまた増えます。",
        "macOS already reserved this space for its next update. Installing the update releases most of it.": "macOS はこの領域を次のアップデートのためにすでに確保しています。アップデートをインストールすると大部分が解放されます。",
        "Open Software Update": "ソフトウェアアップデートを開く",
        "macOS update staging": "macOS アップデートの準備領域",
        "Application": "アプリケーション",
        "App data": "アプリのデータ",
        "macOS": "macOS",
        "Memory swap": "メモリスワップ",
        "Messages history": "メッセージの履歴",
        "Every conversation and attachment Messages ever received. Its own settings trim them safely.": "メッセージが受け取ったすべての会話と添付ファイル。メッセージ自身の設定で安全に整理できます。",
        "Messages keeps every attachment ever received. Its own settings delete old ones safely and can expire messages automatically.": "メッセージは受け取った添付ファイルをすべて保存しています。メッセージ自身の設定で古いものを安全に削除でき、自動的に期限切れにすることもできます。",
        "Review in Storage settings": "ストレージ設定で確認",
        "Mail downloads": "メールのダウンロード",
        "Local copies of mail and attachments. Mail re-downloads what you open.": "メールと添付ファイルのローカルコピー。開いたものはメールが再ダウンロードします。",
        "Mail keeps local copies of messages and attachments and re-downloads them on demand. Its account settings control how much stays.": "メールはメッセージと添付ファイルのローカルコピーを保存し、必要に応じて再ダウンロードします。保存量はアカウント設定で調整できます。",
        "Your photo library and its indexes. Photos manages it, and iCloud can keep originals in the cloud.": "あなたの写真ライブラリとその索引。写真アプリが管理し、iCloud はオリジナルをクラウドに置いておけます。",
        "Photos owns this library, including its thumbnails and search index. iCloud Photos can keep originals in the cloud from Photos' own settings.": "このライブラリはサムネイルや検索索引も含めて写真アプリのものです。iCloud 写真の設定で、オリジナルをクラウドに置いておけます。",
        "Open Photos": "写真を開く",
        "Chrome's on-device AI model": "Chrome のオンデバイス AI モデル",
        "Chrome downloads this model for its built-in AI features and fetches it again when needed.": "Chrome が内蔵 AI 機能のためにダウンロードするモデルです。必要になれば再取得します。",
        "uv cache": "uv のキャッシュ",
        "Trim Locally": "この Mac から整理",
        "Trim Messages on this Mac": "この Mac のメッセージを整理",
        "Messages in iCloud is off, so this Mac holds the only copy. Elbowroom won't touch it.": "iCloud のメッセージがオフのため、この Mac が唯一のコピーを持っています。Elbowroom は触れません。",
        "Message attachments": "メッセージの添付ファイル",
        "Received attachments. They stay in iCloud and on your other devices, and download again when you open old conversations. Ones not yet uploaded to iCloud would be lost.": "受信した添付ファイル。iCloud と他のデバイスには残り、古い会話を開くと再ダウンロードされます。まだ iCloud にアップロードされていないものは失われます。",
        "Message preview caches": "メッセージのプレビューキャッシュ",
        "Thumbnails Messages remakes as you browse.": "閲覧に合わせてメッセージが作り直すサムネイル。",
        "Trim Photos on this Mac": "この Mac の写真を整理",
        "Entire Photos library": "写真ライブラリ全体",
        "The whole library. Deleting the local copy does not delete photos from iCloud. Any photos not yet uploaded from this Mac would be lost. If this Mac never imports photos, nothing is waiting to upload. Photos makes a new empty library the next time it opens.": "ライブラリ全体。ローカルコピーを削除しても iCloud の写真は削除されません。この Mac からまだアップロードされていない写真は失われます。この Mac で写真を取り込んでいなければ、アップロード待ちのものはありません。次回写真アプリを開くと、新しい空のライブラリが作られます。",
        "Shared with You photos": "あなたと共有された写真",
        "Photos from Messages conversations, kept by macOS for Shared with You. It manages its own size.": "メッセージの会話から届いた写真。macOS が「あなたと共有」のために保持し、サイズは自動で管理されます。",
        "Messages keeps these in a hidden library so they appear in Photos' sidebar under Shared with You. Turning off Photos in Messages settings, under Shared with You, removes the copies. The originals stay in your conversations.": "メッセージがこれらを隠しライブラリに保存し、写真アプリのサイドバーの「あなたと共有」に表示します。メッセージの設定にある「あなたと共有」で「写真」をオフにすると、この控えは削除されます。元の写真は会話の中に残ります。",
        "Open Messages": "メッセージを開く",
        "Photo thumbnails": "写真のサムネイル",
        "Thumbnails Photos remakes as you browse. With iCloud optimizing storage, remaking them can download photos again.": "閲覧に合わせて写真アプリが作り直すサムネイル。iCloud でストレージを最適化している場合、作り直しの際に写真を再ダウンロードすることがあります。",
        "Python packages uv keeps for reuse. The next install refetches what a project needs.": "uv が再利用のために保存している Python パッケージ。次のインストールで必要な分を再取得します。",
        "macOS keeps a few local snapshots beside your real backups and thins them on its own. Deleting them frees the space they pin.": "macOS は本来のバックアップとは別にローカルスナップショットをいくつか保ち、自動で間引きます。削除すると、それらが抱えている容量が戻ります。",
        "Full Disk Access": "フルディスクアクセス",
        "Lets the scan read protected folders like Mail and Safari. macOS asks you to grant it in System Settings.": "Mail や Safari などの保護されたフォルダをスキャンで読めるようになります。付与はシステム設定から行います。",
        "Open System Settings": "システム設定を開く",
        "Granted": "許可済み",
        "Hide": "隠す",
        "%d hidden": "%d 件を非表示中",
        "Show": "表示",
        "%@ cache": "%@ のキャッシュ",

        // 11.6 Explainers
        "macOS keeps files it can delete on its own when space runs low. Finder often counts this space as available. Elbowroom lists it separately.": "空きが減ると macOS が自分で消せるファイルです。Finder はこの分を空きに数えることがあります。Elbowroom は分けて表示します。",
        "macOS makes these local backups and thins them on its own. The command below thins them now.": "macOS が作るローカルバックアップで、自動で間引かれます。下のコマンドで今すぐ間引けます。",


        // 11.8 Errors
        "That move didn't finish. Nothing was lost. Try again?": "移動が完了しませんでした。失われたものはありません。もう一度試しますか。",

        // 11.9 Kibi lines (re-authored)
        "Nothing to clean right now.": "今は掃除するものがありません。",
        "No receipts yet.": "控えはまだありません。",
        "No changes this week.": "今週は変化がありません。",
        "No matches.": "見つかりません。",

        // Steward
        "Open Elbowroom": "Elbowroom を開く",
        "Reclaimable now: %@": "今すぐ取り戻せる分: %@",
        "Pause a while": "しばらく休ませる",
        "Quit Elbowroom": "Elbowroom を終了",
        "Room for an update": "アップデートのための空き",
        "The update needs %1$@ more than is free. This plan clears %2$@ in about %3$d minutes.": "アップデートには空きがあと %1$@ 足りません。この計画で約 %3$d 分、%2$@ を空けられます。",
        "Also worth a look (through their own apps, not counted above)": "あわせて確認する価値のあるもの(各アプリから操作。上の合計には含みません)",
        "Plan for an update": "アップデートに備える",
        "Room for the update": "アップデートのための空き",
        "%@ free": "空き %@",
        "Free": "空き",
        "%1$@ free of %2$@": "%2$@ 中 空き %1$@",
        "Ready to reclaim": "取り戻せる容量",
        "Caches and derived data apps rebuild on their own. Nothing personal is touched without you choosing it.": "キャッシュとビルド生成物は、アプリが自分で作り直します。あなたが選ばない限り、個人のファイルには触れません。",
        "Biggest wins right now": "いま効き目の大きい項目",
        "All %d items": "全 %d 件",
        "Add to Plan": "計画に追加",
        "In plan": "計画に追加済み",
        "Growing this week": "今週の増減",
        "↓ means Elbowroom already trimmed it back.": "↓ は Elbowroom がすでに整理し終えた分です。",
        "The next macOS update needs about %1$@ free. You have %2$@, so you are covered.": "次の macOS アップデートには約 %1$@ の空きが必要です。現在 %2$@ あるので大丈夫です。",
        "All time": "累計",
        "returned to this Mac.": "をこの Mac に取り戻しました。",
        "sorted by size": "サイズ順",
        "Everything here is rebuilt or recoverable": "ここにあるものは、作り直せるか元に戻せます",
        "click a region to dig in": "クリックで掘り下げる",
        "%1$@ scanned · %2$@ free": "スキャン済み %1$@ · 空き %2$@",
        "tint = tier · area = size": "色 = 安全度 · 面積 = サイズ",
        "Switch light and dark": "ライトとダークを切り替え",
        "The current runtime. Xcode downloads about %@ again before simulators next run.": "現在使用中のランタイムです。削除すると、次にシミュレータを使う前に Xcode が約 %@ を再ダウンロードします。",
        "Full sweep of everything unused": "未使用のものを一括整理",
        "docker system prune removes every unused image, container, volume, and build cache in one pass.": "docker system prune が、未使用のイメージ、コンテナ、ボリューム、ビルドキャッシュを一度に削除します。",
        "Simulator": "シミュレータ",
        "Runtimes, simulated devices, and caches for Xcode's simulators, together.": "Xcode のシミュレータのランタイム、仮想デバイス、キャッシュをまとめた項目です。",
        "Simulator dyld caches": "シミュレータの dyld キャッシュ",
        "Prebuilt loader caches. The next simulator boot remakes what it needs.": "事前構築されたローダキャッシュです。次にシミュレータを起動したとき、必要な分が作り直されます。",

        // Lenses
        "Click to look closer": "クリックで詳しく見る",
        "Reclaim All": "すべて取り戻す",
        "Photos, VMs, installers, and old downloads hide in here. Lenses name them.": "写真、仮想マシン、インストーラ、古いダウンロードがこの中に隠れています。レンズが名前を付けます。",
        "%@ named so far": "ここまでに %@ に名前が付きました",
        "No additional storage groups recognized yet. Everything else may still contain space you can reclaim.": "追加のストレージ分類はまだ見つかっていません。「そのほかすべて」にも、空けられる容量が残っている可能性があります。",
        "%1$d photos, %2$d videos · %3$@": "写真 %1$d 枚、動画 %2$d 本 · %3$@",
        "%@ is already installed": "%@ はインストール済みです",
        "%d large file": "大きいファイル %d 件",
        "%d large files": "大きいファイル %d 件",
        "Byte-identical in both places, verified": "両方の場所でバイト単位で同一(確認済み)",
        "Its unpacked folder sits right beside it": "展開済みのフォルダがすぐ隣にあります",
        "%@ project": "%@ プロジェクト",
        "Nothing inside touched since %@": "%@ から中身に変化はありません",
        "Last used %@": "最終使用は %@",
        "Re-downloadable from its hub": "配布元から再ダウンロードできます",
        "Reinstalls from Steam · updated %@": "Steam から再インストール可能 · 更新は %@",
        "Named by a lens": "レンズが名前を付けた項目",
        "Found inside Everything else. You saw what it is; you decide.": "「そのほか」の中で見つかりました。正体を確認した上で、あなたが決めてください。",

        // Ask Kibi
        "AI guess": "AI の推測",
        "Double-check before acting.": "実行の前にご自身でも確かめてください。",
        "Not confident. Contents:": "確信が持てません。中身は次のとおりです:",
        "Analyzing": "解析中",
        "Explain": "解析",
        "Explain is ready. Click the sparkle on an unrecognized folder in the Map.": "解析機能は使えます。マップで未分類フォルダのアイコンを押してください。",
        "Explain appears once Apple Intelligence is on in System Settings.": "システム設定で Apple Intelligence をオンにすると、解析機能が使えます。",
        // Chrome
        "Overview": "概要",
        "Map": "マップ",
        "Items": "項目",
        "History": "履歴",
        "Copied": "コピーしました",
        "Copy Command": "コマンドをコピー",
        "Show me": "見せて",
        "Reveal in Finder": "Finder に表示",
        "Elbowroom has returned %@ to this Mac": "Elbowroom はこの Mac に %@ を返してきました",
        "one square is about %@ at this zoom": "このズームでは 1 マスが約 %@",
        "+ %1$d smaller · %2$@": "+ 小さいもの %1$d 件 · %2$@",
        "Checking what changed": "変化を確認中",
        "Search": "検索",
        "Scan again": "もう一度スキャン",
        "Settings": "設定",
        "Everything else": "そのほかすべて",
        "Freed through the owning app, not by Elbowroom directly.": "Elbowroom が直接ではなく、持ち主のアプリを通して空ける分です。",
        "Hide for 30 days": "30 日間隠す",
        "Test-run simulator clones": "テスト実行用シミュレータの複製",
        "Copies xcodebuild makes for parallel testing. Tests remake them when needed.": "並列テストのために xcodebuild が作る複製です。必要になればテストが作り直します。",
        "Clear filter": "絞り込みを解除",
        "%d item": "%d 件",
        "%d items": "%d 件",
        "Name": "名前",
        "Size": "サイズ",
        "Tier": "安全度",
        "Last touched": "最終使用",
        "Put Back": "元に戻す",
        "Export CSV": "CSV を書き出す",
        "Room to build.": "つくる余白を。",

        // Staleness
        "touched today": "今日使いました",
        "untouched %d day": "%d 日 未使用",
        "untouched %d days": "%d 日 未使用",
        "untouched %d weeks": "%d 週間 未使用",
        "untouched %d month": "%dか月 未使用",
        "untouched %d months": "%dか月 未使用",
        "untouched %d year": "%d 年 未使用",
        "untouched %d years": "%d 年 未使用",
        "today": "今日",
        "yesterday": "昨日",
        "%d days ago": "%d 日前",
        "%d weeks ago": "%d 週間前",
        "%d months ago": "%dか月前",
        "%d years ago": "%d 年前",

        // Atlas identities
        "Xcode build products": "Xcode のビルド生成物",
        "Intermediate build files. Xcode remakes them on the next build.": "ビルドの中間ファイルです。次のビルドで Xcode が作り直します。",
        "Xcode archives": "Xcode のアーカイブ",
        "Past app builds and their debug symbols. Keep them if you shipped those builds.": "過去のアプリビルドとデバッグシンボルです。配布したビルドなら残しておきましょう。",
        "Device support files": "実機サポートファイル",
        "Debug files copied from each iPhone or iPad you plugged in. They copy over again on the next connection.": "接続した iPhone や iPad からコピーされたデバッグ用ファイルです。次に接続すればまたコピーされます。",
        "Simulator devices": "シミュレータのデバイス",
        "The simulated iPhones and iPads Xcode created, with their apps and data.": "Xcode が作った仮想の iPhone や iPad と、その中のアプリとデータです。",
        "Simulator runtimes": "シミュレータのランタイム",
        "Re-downloadable OS images for the simulator. Xcode's own panel removes them safely.": "再ダウンロードできるシミュレータ用 OS イメージです。Xcode 自身の画面から安全に削除できます。",
        "Simulator caches": "シミュレータのキャッシュ",
        "Scratch files the simulator refills as it runs.": "シミュレータが動きながら作り直す作業ファイルです。",
        "Swift package caches": "Swift パッケージキャッシュ",
        "Downloaded package sources. They download again when a build needs them.": "ダウンロード済みのパッケージソースです。ビルドが必要とすれば再ダウンロードされます。",
        "Swift package build folder": "Swift パッケージのビルドフォルダ",
        "Build output for a Swift package. The next build remakes it.": "Swift パッケージのビルド出力です。次のビルドで作り直されます。",
        "SwiftUI preview data": "SwiftUI プレビューのデータ",
        "Simulators and caches used by Xcode previews. They rebuild on the next preview.": "Xcode プレビューが使うシミュレータとキャッシュです。次のプレビューで作り直されます。",
        "Xcode caches": "Xcode のキャッシュ",
        "Scratch files Xcode refills as it runs.": "Xcode が動きながら作り直す作業ファイルです。",
        "JavaScript packages": "JavaScript パッケージ",
        "Installed packages for one project. The next install remakes the folder.": "このプロジェクトにインストールされたパッケージです。次のインストールでフォルダごと作り直されます。",
        "npm cache": "npm キャッシュ",
        "Downloaded package archives. npm refills this as you install.": "ダウンロード済みのパッケージアーカイブです。インストールのたびに npm が補充します。",
        "pnpm store": "pnpm ストア",
        "The shared package store pnpm links projects to. It refills on install.": "pnpm が各プロジェクトへリンクする共有ストアです。インストール時に補充されます。",
        "Yarn cache": "Yarn キャッシュ",
        "Downloaded package archives. Yarn refills this as you install.": "ダウンロード済みのパッケージアーカイブです。インストールのたびに Yarn が補充します。",
        "Bun cache": "Bun キャッシュ",
        "Downloaded package archives. Bun refills this as you install.": "ダウンロード済みのパッケージアーカイブです。インストールのたびに Bun が補充します。",
        "Rust build folder": "Rust のビルドフォルダ",
        "Compiled output for one project. The next cargo build remakes it.": "このプロジェクトのコンパイル結果です。次の cargo build で作り直されます。",
        "Cargo registry": "Cargo レジストリ",
        "Downloaded crate sources shared by your Rust projects. Cargo refills it on the next fetch.": "Rust プロジェクトが共有するクレートのソースです。次の取得時に Cargo が補充します。",
        "Cargo git checkouts": "Cargo の git チェックアウト",
        "Git dependencies cargo cloned. They clone again when needed.": "cargo がクローンした git 依存です。必要になればまたクローンされます。",
        "Homebrew downloads": "Homebrew のダウンロード",
        "Installer archives Homebrew already used. It downloads fresh ones when needed.": "Homebrew が使い終えたインストーラです。必要になれば新しく取得します。",
        "Homebrew old versions": "Homebrew の古いバージョン",
        "Older versions kept beside the current ones. brew cleanup removes them safely.": "現行版のとなりに残った古いバージョンです。brew cleanup が安全に片づけます。",
        "Docker Desktop data": "Docker Desktop のデータ",
        "Docker's virtual disk with your images, containers, and volumes.": "イメージ、コンテナ、ボリュームが入った Docker の仮想ディスクです。",
        "OrbStack data": "OrbStack のデータ",
        "OrbStack's virtual disk with your machines, images, and volumes.": "マシン、イメージ、ボリュームが入った OrbStack の仮想ディスクです。",
        "iPhone and iPad backups": "iPhone と iPad のバックアップ",
        "Full device backups Finder made. Finder's own panel manages them.": "Finder が作ったデバイスの完全バックアップです。Finder 自身の画面で管理します。",
        "Trash": "ゴミ箱",
        "Files you already deleted. Emptying the Trash frees them for good.": "すでに削除したファイルです。ゴミ箱を空にすれば完全に片づきます。",
        "App cache": "アプリのキャッシュ",
        "Scratch files this app refills as it runs.": "このアプリが動きながら作り直す作業ファイルです。",
        "Purgeable space": "パージ可能な領域",
        "Local Time Machine snapshots": "ローカル Time Machine スナップショット",
        "Hugging Face models": "Hugging Face モデル",
        "Downloaded model weights. They download again on the next use.": "ダウンロード済みのモデルです。次に使うときにまたダウンロードされます。",
        "Ollama models": "Ollama モデル",
        "Downloaded model weights. ollama pull brings any of them back.": "ダウンロード済みのモデルです。ollama pull でいつでも戻せます。",
        "LM Studio models": "LM Studio モデル",

        // Teach flows
        "Simulator runtimes and devices": "シミュレータのランタイムとデバイス",
        "Xcode owns these. Its own panel removes them safely and can download them again later.": "これは Xcode の持ちものです。Xcode 自身の画面から安全に削除でき、あとで再ダウンロードもできます。",
        "Open Xcode's Components panel": "Xcode の Components 画面を開く",
        "List the installed runtimes, then delete one by its id.": "インストール済みランタイムを一覧し、id を指定して削除します。",
        "Docker owns this virtual disk. Removing files inside it by hand corrupts it.": "この仮想ディスクは Docker の持ちものです。中のファイルを手で消すと壊れます。",
        "Open Docker Desktop": "Docker Desktop を開く",
        "Removes stopped containers, unused networks, and all unused images.": "停止中のコンテナ、未使用のネットワーク、未使用のイメージをすべて削除します。",
        "Prune deletes every image no container is using. Pulling them back takes time and bandwidth.": "prune はどのコンテナも使っていないイメージをすべて削除します。取り直すには時間と通信量がかかります。",
        "OrbStack owns this virtual disk. Its own settings reclaim space safely.": "この仮想ディスクは OrbStack の持ちものです。OrbStack の設定から安全に空けられます。",
        "Open OrbStack": "OrbStack を開く",
        "Prune deletes every image no container is using.": "prune はどのコンテナも使っていないイメージをすべて削除します。",
        "Asks macOS to thin snapshots until about 20 GB frees up.": "約 20 GB 空くまでスナップショットを間引くよう macOS に頼みます。",
        "Finder owns these backups. Its own panel shows each one and deletes them safely.": "バックアップは Finder の持ちものです。Finder の画面で 1 つずつ確認して安全に削除できます。",
        "Open Finder's backup list": "Finder のバックアップ一覧を開く",
        "You already deleted these files. Emptying the Trash frees them for good.": "すでに削除したファイルです。ゴミ箱を空にすれば完全に片づきます。",
        "Open the Trash": "ゴミ箱を開く",
        "Time Machine": "Time Machine",
        "Time Machine owns this. Its settings control what it keeps.": "これは Time Machine の持ちものです。何を残すかは Time Machine の設定で決まります。",
        "Open Time Machine settings": "Time Machine の設定を開く",
        "Homebrew owns the Cellar. brew cleanup removes old versions safely and keeps what is linked.": "Cellar は Homebrew の持ちものです。brew cleanup が古いバージョンを安全に削除し、リンク中のものは残します。",
        "Removes old versions and stale downloads of everything installed.": "インストール済みのものの古いバージョンと古いダウンロードを削除します。",

        // Settings
        "General": "一般",
        "Receipts": "控え",
        "Privacy": "プライバシー",
        "Play sounds": "サウンドを鳴らす",
        "Low-space alert": "空き容量の警告",
        "%d GB free": "空き %d GB",
        "Connection speed": "回線速度",
        "Measure Again": "もう一度計測",
        "The connection speed only phrases re-download times. Nothing uploads.": "回線速度は再ダウンロード時間の表現にだけ使います。何も送信されません。",
        "Language": "言語",
        "Follow the system": "システムに合わせる",
        "Takes effect after Elbowroom reopens.": "Elbowroom を開き直すと反映されます。",
        "Share anonymous usage statistics": "匿名の利用統計を送る",
        "Aggregates only: event names, byte counts, durations. No paths, no file names, no device fingerprint. Stored locally where you can read them.": "集計のみ: イベント名、バイト数、所要時間。パスもファイル名も端末の指紋も含みません。手元で読める場所に保存されます。",
        "Show the local analytics file": "ローカルの統計ファイルを表示",
        "and %d more": "ほか %d 件",
        "in Trash": "ゴミ箱に",
        "emptied": "空にした",
        "restored": "戻した",
        "deleted": "削除済み",
        "grew": "増加",
        "freed": "解放",
    ]
}
